apiVersion: batch/v1
kind: Job
metadata:
  name: ut-migration-{{ .Release.Revision }}
  namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: migration
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        command: ['sh', '-c', 'python manage.py makemigrations && python manage.py migrate']
        envFrom:
        - secretRef:
            name: {{ .Values.secretRef }}
        - configMapRef:
            name: {{ .Values.configMapRef }}
      restartPolicy: Never
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
  backoffLimit: {{ .Values.job.backoffLimit }}

