apiVersion: v1
kind: Service
metadata:
  name: useless-tools-service
  namespace: useless-tools
spec:
  selector:
    app: useless-tools
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
